### DISCUSSION TITLE
Docker (latest) gives error about Onedrive client: Your onedrive client version is obsolete and unsupported

### DISCUSSION THREAD

**Discussion by bossanova808** [abraunegg/onedrive#2163] [General]
```
# Launching onedrive
Configuration file successfully loaded
WARNING: Your onedrive client version is obsolete and unsupported. Please upgrade your client version.
```

Docker def is:

```
    onedrive:
        container_name: onedrive
        image: driveone/onedrive:latest
        environment:
            - ONEDRIVE_UID=${UID}
            - ONEDRIVE_GID=${GUID}
            # - ONEDRIVE_RESYNC=1
            # - ONEDRIVE_VERBOSE=1
            # - ONEDRIVE_DOWNLOADONLY=1            
        volumes:
            - ${ONEDRIVE_CONFIG}:/onedrive/conf:rw
            - ${ONEDRIVE_FOLDER}:/onedrive/data:rw
        # this one is manually started and stopped overnight as it places a lot of load on this puny machine..
        #restart: unless-stopped
```
