### DISCUSSION TITLE
first time authentication from Docker Compose using auth files arg

### DISCUSSION THREAD

**Discussion by Rathna-K** [abraunegg/onedrive#2349] [Q&A] [answered]
Reference Issue: https://github.com/abraunegg/onedrive/issues/1557
I am trying to do the auth with files and thru docker compose but I am running in to an error.
### Compose command:
```
- --auth-files authUrl:responseUrl
- --verbose
volumes:
- /home/onedrive/conf:/onedrive/conf
- /home/onedrive/data:/onedrive/data
```

I see, it recognized the verbose command but not the later. Do I have the commands correct in my compose?

Here is the log when I start the container.
```
onedrive | Base Args: --monitor
onedrive | # Launching onedrive
onedrive | Using 'user' Config Dir: /home/onedrive/.config/onedrive
onedrive | Using 'system' Config Dir: /etc/onedrive
onedrive | No user or system config file found, using application defaults
onedrive | Unrecognized option --auth-files authUrl:responseUrl
onedrive | Try 'onedrive -h' for more information
onedrive exited with code 1
```

**Comment by abraunegg** [comment, marked as answer]
@Rathna-K 
So there are a number of issues here.

1. `Unrecognized option --auth-files`
2. `authUrl:responseUrl`

Firstly, `--auth-files` should be a recognised option. How are you building your Docker container and from *what* source? You need to consume the Docker container from https://hub.docker.com/r/driveone/onedrive and nowhere else. If your Docker container is not understanding this option, you are not using the correct Docker container.

The second one is essentially how you have interpreted the documentation and prior questions+answers regarding the use of this option.

What you have done is *literally* follow the documentation - without substituting the items with the actual items required as per the documentation. 

![image](https://user-images.githubusercontent.com/4956234/226724196-59d35dab-d090-4ce6-88b3-180a9721b9cb.png)

The `authUrl:responseUrl` items are key|value pairs and need to point to specific files that your system has access to, for example:
```
--auth-files /path/to/where/my/auth/url/file/sits/authURLFile:/path/to/where/my/auth/response/file/sits/responseUrlFile
```
The contents of these files need to be, for example:
### authURLFile
```
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=d50ca740-c83f-4d1b-b616-12c519384f0c&scope=Files.ReadWrite%20Files.ReadWrite.All%20Sites.ReadWrite.All%20offline_access&response_type=code&prompt=login&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient
```

The application will *write* the Authentication URL to this file - you do not need to add the content in there - but the path to where this file exists must exist so that the URL can be written to this file.

You then can use this URL, from this file and grab the response.

### responseUrlFile
```
https://login.microsoftonline.com/common/oauth2/nativeclient?code=<redacted>
```

This file should contain your *actual* authentication response from OneDrive when you use the authentication URL above.

The application will *wait* for the existence of the `/path/to/where/my/auth/response/file/sits/responseUrlFile` before attempting to perform the authentication of the client.

**Comment by Rathna-K** [comment]
Here is my full compose file:

```
services:
  onedrive:
    image: driveone/onedrive:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: "onedrive"
    restart: always
    environment:
      - ONEDRIVE_UID=xxx
      - ONEDRIVE_GID=xxx
    command:
      - --auth-files /onedrive/conf/authUrl:/onedrive/conf/responseUrl
      - "--auth-files /onedrive/conf/authUrl:/onedrive/conf/responseUrl" <---tried the same with double quotes as well like this in a separate run
      - --verbose
    volumes: 
      - /home/onedrive/conf:/onedrive/conf
      - /home/onedrive/data:/onedrive/data

networks:
  docker-network:
    external: true
```

I also have created two folders in my home dir: conf and data and two files inside conf: authUrl, responseUrl 

When a new container is spun up without doing anything else , here is the console output : 

```
onedrive  | usermod: no changes
onedrive  | Base Args: --monitor
onedrive  | # Launching onedrive
onedrive  | Using 'user' Config Dir: /home/onedrive/.config/onedrive
onedrive  | Using 'system' Config Dir: /etc/onedrive
onedrive  | No user or system config file found, using application defaults
onedrive  | Unrecognized option --auth-files /onedrive/conf/authUrl:/onedrive/conf/responseUrl
onedrive  | Try 'onedrive -h' for more information
```


I think the option may not get properly parsed  or maybe I am missing something here ?
