### DISCUSSION TITLE
Upload only files to business shared folder

### DISCUSSION THREAD

**Discussion by Rfferrao87** [abraunegg/onedrive#2378] [Q&A] [answered]
Greetings,

I don't know if it's intended this way, but I'm having trouble configuring the client to be able to upload only files to a business shared folder; disabling the `upload_only` option makes it sync properly, but this won't work for what I'm trying to set up. Is there a way to solve this?

I'm using the Docker container as per the documentation specifies. The `docker-compose` and remaining pertinent files are specified below:

- **docker-compose.yml**
```yml
version: "3"
services:
    onedrive:
        image: driveone/onedrive:latest
        restart: unless-stopped
        environment:
            - ONEDRIVE_UID=1001
            - ONEDRIVE_GID=1001
            - ONEDRIVE_UPLOADONLY=1
        volumes:
            - onedrive_conf:/onedrive/conf
            - ${ONEDRIVE_DATA_DIR}:/onedrive/data
volumes:
    onedrive_conf:
```

- **business_shared_folders**
```sh
# 'Backups' business shared folder
Backups
```

- **config**
```ini
# Configuration for OneDrive Linux Client
# This file contains the list of supported configuration fields
# with their default values.
# All values need to be enclosed in quotes
# When changing a config option below, remove the '#' from the start of the line
# For explanations of all config options below see docs/USAGE.md or the man page.
#
no_remote_delete = "true"
sync_business_shared_folders = "true"
```
