### DISCUSSION TITLE
Docker container goes straight to `Enter the response uri: Invalid response uri entered`

### DISCUSSION THREAD

**Discussion by addohm** [abraunegg/onedrive#2656] [Q&A] [answered]
What would cause the container to follow this sequence where theres no opportunity to actually enter a response URL?  It's always worked for me in the past.  I've tried several different shells.
I set up the docker container with docker compose as a part of a full stack...
```yaml
...
    onedrive:
        image: driveone/onedrive:latest
        container_name: onedrive
        restart: unless-stopped
        environment:
            - ONEDRIVE_UID=1000
            - ONEDRIVE_GID=1000
            - ONEDRIVE_RESYNC=0
        volumes:
            - /mnt/usb/onedrive/conf:/onedrive/conf
            - /mnt/usb/onedrive/data:/onedrive/data
...
```
Then start the container in interactive mode to authorize it...
```bash
docker start onedrive --interactive
usermod: no changes
Base Args: --monitor
# Launching onedrive
Configuring Global Azure AD Endpoints
Authorize this app visiting:
big-long-url
**Enter the response uri: Invalid response uri entered**
Could not initialize the OneDrive API
```

I never actually get the opportunity to enter a response URL and the container just goes into what appears to be a boot loop.

edit: I've also tried using the docker compose create method, the container by itself, so that I am the first one start the container but get the same results.  I've also tried using several of the startup flags to try and debug with no luck.

Even when trying to utilize `ONEDRIVE_AUTHFILES` it behaves the same way, but without offering up a URL at all.

```yaml
- ONEDRIVE_AUTHFILES="/onedrive/conf/auth.txt:/onedrive/conf/response.txt"
```

Checking for auth.txt it is not created.  If I create it and restart, it doesn't get filled out with anything.  I have to think I'm missing something glaringly obvious at this point.

```bash
# We are using auth files to perform authentication
# Adding --auth-files ARG
# We are providing the auth response directly to perform authentication
# Adding --auth-response ARG
# Launching onedrive
Configuring Global Azure AD Endpoints
Invalid response uri entered
Could not initialize the OneDrive API
usermod: no changes
Base Args: --monitor
# We are using auth files to perform authentication
# Adding --auth-files ARG
# We are providing the auth response directly to perform authentication
# Adding --auth-response ARG
# Launching onedrive
Configuring Global Azure AD Endpoints
Invalid response uri entered
Could not initialize the OneDrive API
```

I was able to work around this by bypassing the entrypoint and manually running `onedrive`.  It gave me a url, prompted, and waited for me to respond this way.  Very strange and new behavior.  Given there hasn't been any updates since June of last year, its definetly something on my end.

**Comment by abraunegg** [comment, marked as answer]
@addohm 
This is *not* the first time you have had this issue - it will be your *permissions* for `/mnt/usb/onedrive/conf:/onedrive/conf` that is getting messed up *again*

Please ensure that your permissions are correct - that the user id that the container is running as, has permissions to the config folder.

**Comment by M4jx** [comment]
I'm facing the same problem, however, I am using the `ONEDRIVE_AUTHRESPONSE` environment variable to directly provide the URL response.

This is my `docker-compose.yml` file that I deploy with `docker stack deploy --compose-file docker-compose.yml mystack` command.

```
version: "3.8"

volumes:
  onedrive_conf:

services:
  onedrive:
    image: driveone/onedrive:edge
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - ONEDRIVE_UID=1000
      - ONEDRIVE_GID=1000
      - ONEDRIVE_VERBOSE=1
      - ONEDRIVE_DEBUG=1
      - ONEDRIVE_AUTHRESPONSE="https://login.microsoftonline.com/common/oauth2/nativeclient?code=xxxxx"
    volumes:
      - onedrive_conf:/onedrive/conf
```

This is the docker logs:

```
Base Args: --monitor

# We are being verbose

# Adding --verbose

# We are performing debug output

# Adding --verbose --verbose

# We are providing the auth response directly to perform authentication

# Adding --auth-response ARG

# Launching onedrive

Configuring Global Azure AD Endpoints

Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=d50ca740-c83f-4d1b-b616-12c519384f0c&scope=Files.ReadWrite%20Files.ReadWrite.All%20Sites.ReadWrite.All%20offline_access&response_type=code&prompt=login&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: Invalid response uri entered

Could not initialize the OneDrive API
```

Any idea of what this issue might be due to?

**Comment by abraunegg** [comment]
@M4jx 
Your filesystem permissions are wrong for your config Docker path

**Reply by M4jx** [reply]
Thanks for the hint.

It seems to be a common issue people face with the permissions of docker volumes.
I have solved the issue by creating an `init` container to initialize the volume with correct permissions as commented [here](https://github.com/docker/compose/issues/3270#issuecomment-1245819741) and make the onedrive container depend on it.

```
services:
  onedrive-init:
    image: node:16
    user: root
    volumes:
      - onedrive_conf:/onedrive/conf
    command: chown -R 1000:1000 /onedrive/conf
```

**Comment by Djeex** [comment]
I have the same problem, my onedrive_conf permissions are OK (1000:1000). Can't find the problem.

```logs
onedrive  | usermod: no changes
onedrive  | # Running container as user: onedrive
onedrive  | # Base Args: --confdir
onedrive  | # We run in Monitor Mode
onedrive  | # Adding --monitor
onedrive  | # We are synchronizing in download-only mode
onedrive  | # Adding --download-only
onedrive  | # Changing ownership permissions on /onedrive/data and /onedrive/conf to onedrive:onedrive
onedrive  | # Launching 'onedrive' as onedrive via gosu
onedrive  | Reading configuration file: /onedrive/conf/config
onedrive  | Configuration file successfully loaded
onedrive  | Using IPv4 and IPv6 (if configured) for all network operations
onedrive  | Attempting to contact Microsoft OneDrive Login Service
onedrive  | Successfully reached Microsoft OneDrive Login Service
onedrive  | Configuring Global Azure AD Endpoints
onedrive  | Authorise this application by visiting:
onedrive  | 
onedrive  | https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=[REDACTED]&scope=Files.ReadWrite%20Files.ReadWrite.All%20Sites.ReadWrite.All%20offline_access&response_type=code&prompt=login&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient
onedrive  | 
onedrive  | Enter the response uri from your browser: An empty or invalid response uri was entered
onedrive  | The OneDrive API could not be initialised
onedrive exited with code 1
```

Compose :
```yaml
version: "3"
services:
  onedrive:
    image: driveone/onedrive:edge
    container_name: onedrive
    restart: unless-stopped
    environment:
      - ONEDRIVE_UID=${PUID}
      - ONEDRIVE_GID=${PGID}
      - ONEDRIVE_DOWNLOADONLY=1
    volumes:
      - /docker/onedrive/onedrive_conf:/onedrive/conf
      - ${ONEDRIVE_DATA_DIR}:/onedrive/data
```
.env :
```properties
PUID=1000
PGID=1000
ONEDRIVE_DATA_DIR=/dpool/data/onedrive
```

Any ideas ?
