### DISCUSSION TITLE
Docker compose with Portainer

### DISCUSSION THREAD

**Discussion by BJOHEI** [abraunegg/onedrive#2756] [Q&A] [answered]
Been absolutely stumped and I cant figure out how to go about using docker compose to get it running. Got some help from reddit with 
```
services:
  onedrive:
    image: driveone/onedrive:edge
    container_name: onedrive
    environment:
      - ONEDRIVE_UID:1000
      - ONEDRIVE_GID:1000 
      - TZ=Europe/Oslo
    volumes:
      - /srv/dev-disk-by-uuid-10f713a6-3ade-43b8-936d-11820d50eb4f/onedrive/conf:/onedrive/conf #configuration data
      - /srv/dev-disk-by-uuid-10f713a6-3ade-43b8-936d-11820d50eb4f/onedrive/imagebackup/:/onedrive/data #stored data
    restart: unless-stopped
```

Im running into a auth limbo where I have nowhere to input the auth-link.
Using the above code, can I download the `config` file into `xxxxxx/onedrive/conf` and modify it and it will pull what it needs from it, or do I have to put the config file in another path?
The line `#stored data`, this is where the data is stored I assume, is there a way to tell the compose file that I only want say `Pictures/imagebackup` in my onedrive to be monitored? 

TIA
