### DISCUSSION TITLE
Clarification about the file .nosync

### DISCUSSION THREAD

**Discussion by icvdok** [abraunegg/onedrive#2765] [Q&A] [answered]
Hello, I'm using the onedrive client in a docker environment with docker compose. My setup is working with basic configuration (I'm not an expert). The docker filesystem consist of two mounted folders on my NAS via DFS. I was reading the docs about the risk related the remote mount and I've try to apply the mitigation as documented adding the .nosync file before start the compose and related mounted volumes and adding the check_nomount = "true" and check_nosync = "true" in the config file.

When the docker start, report `ERROR: .nosync file found. Aborting synchronization process to safeguard data.`. Removing it, the sync works.

Where I'm wrong? The doc is not fully clear to me, maybe someone can help me. Thanks in advance

**Comment by abraunegg** [comment]
@icvdok 
> The docker filesystem consist of two mounted folders on my NAS via DFS.

To assist with answering this, can you draw up a diagram on exactly how you are 'dong things' ?

* Are you running Docker on your NAS
* Are you running Docker on another system
* Are you mounting your 'data' folder somewhere on your other system where Docker is running and then specifying that path
* Are you directly specifying your NAS folder in your Docker configuration
* Something completely different

It is unclear on how you have set things up ..... once that is a little clearer - some advice can be given

**Comment by icvdok** [comment]
hello, sorry, I was not clear enough, here a simple diagram of my setup
![image](https://github.com/user-attachments/assets/b2e2c09c-b8b3-4633-b017-2e7cccc74486)

Hope that this help to clarify.

**Comment by icvdok** [comment]
In addition, here the docker-compose file I'm using:

```
services:
  onedrive:
    image: driveone/onedrive:edge
    restart: unless-stopped
    container_name: onedrive
    environment:
      - ONEDRIVE_UID=1000
      - ONEDRIVE_GID=1000
      #- ONEDRIVE_RESYNC=1
      - ONEDRIVE_SINGLE_DIRECTORY="documents"
    volumes: 
      - od_conf:/onedrive/conf
      - od_data:/onedrive/data
    networks:
      default:
        ipv4_address: 170.22.0.10   
volumes:
  od_conf:
    name: nfs_onedrive_conf
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=qnap.lan,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
      device: ":_docker/_onedrive/onedrive"
  od_data:
    name: nfs_onedrive_data
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=qnap.lan,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
      device: ":_docker/_onedrive/onedrive_conf"
networks:
  default:
    name: net_onedrive
    ipam:
      config:
        - subnet: 170.22.0.0/24
          gateway: 170.22.0.1
```
