### DISCUSSION TITLE
Error: 127 with libcurl and Docker

### DISCUSSION THREAD

**Discussion by vaidastal** [abraunegg/onedrive#2930] [Q&A] [answered]
Hello, 

I have weird issue with onedrive sync. I have been using it lately and all was fine. This evening I reinstalled Debian, formatted system partition, but remounted my home partition with some of my data.

After this, I tried to run docker-compose files of my containers and all of them were OK, except onedrive...

It throws me an error:

```
# Running container as user: onedrive
# Base Args: --monitor
# Changing ownership permissions on /onedrive/data and /onedrive/conf to onedrive:onedrive
# Launching 'onedrive' as onedrive via gosu
/usr/local/bin/onedrive: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
ERROR: 127
```

I have tried to reset Docker, delete entire contents of /var/lib/docker etc., prune everything, but I fail to run this container. The same error I get running directly via docker, i.e. not with a compose.

I am really frustrated as I really thought that Docker will be the last source of problems in this system reinstall..

Thanks.

**Comment by abraunegg** [comment]
@vaidastal 
That is an odd issue for sure.

**Question:** What Docker container are you using ? What does your docker-compose file look like ?

**Reply by vaidastal** [reply]
Hey,

```
version: "3"

services:
    onedrive_personal:
        image: driveone/onedrive:edge
        container_name: onedrive_personal
        restart: unless-stopped
        environment:
            - ONEDRIVE_UID=1000
            - ONEDRIVE_GID=1000
            #- ONEDRIVE_RESYNC=1
        volumes:
            - /home/user/config/docker/onedrive_sync/personal/conf:/onedrive/conf
            - /home/user/data/onedrive:/onedrive/data
```

Docker version 20.10.24+dfsg1, build 297e128

It is older version installed from apt.
