### DISCUSSION TITLE
sync_dir kept defaulting to ~/OneDrive despite /onedrive/conf is set to "/onedrive/data" - and hence all files are stored inside docker container and not mapped volume

### DISCUSSION THREAD

**Discussion by fliptoback** [abraunegg/onedrive#3266] [Q&A] [answered]
I have the following docker-compose file:

```
 version: "3.7"
 services:
   onedrive_user3:
     image: driveone/onedrive:latest
     container_name: onedrive_user3
     stdin_open: true # docker run -i
     tty: true        # docker run -t
     environment:
       - ONEDRIVE_UID=1026
       - ONEDRIVE_GID=100      
     volumes:
       - /volume1/docker/onedrive_user3:/onedrive/conf      
       - /volume2/onedrive2/johndoe:/onedrive/data
     command: --monitor --confdir /onedrive/conf  # Auto sync in monitor mode
     restart: unless-stopped
```

The container was created successfully - but when i enter into the terminal of the docker container and type 

onedrive --display-config, 

I see:

```
root@b379d8da7819:/# onedrive --display-config                                   
 Application version                          = onedrive v2.5.5                   
 Compiled with                                = LDC 2100                          
 Curl version                                 = libcurl/8.12.1 OpenSSL/3.0.15 zlib /1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.3 libpsl/0.21.2 libssh2/1.10.0 nghttp 2/1.52.0 librtmp/2.3 OpenLDAP/2.5.13                                             
 User Application Config path                 = /root/.config/onedrive            
 System Application Config path               = /etc/onedrive                     
 Applicable Application 'config' location     = /root/.config/onedrive/config     
 Configuration file found in config location  = false - using application defaults
 Applicable 'sync_list' location              = /root/.config/onedrive/sync_list  
 Applicable 'items.sqlite3' location          = /root/.config/onedrive/items.sqlite3                                                                               
 Config option 'drive_id'                     =                                   
 Config option 'sync_dir'                     = ~/OneDrive                        
 Config option 'enable_logging'               = false                             
 Config option 'log_dir'                      = /var/log/onedrive                 
 Config option 'disable_notifications'        = false                             
 Config option 'skip_dir'                     =                                   
 Config option 'skip_dir_strict_match'        = false                             
 Config option 'skip_file'                    = ~*|.~*|*.tmp|*.swp|*.partial      
 Config option 'skip_dotfiles'                = false                             
 Config option 'skip_symlinks'                = false                             
 Config option 'monitor_interval'             = 300                               
 Config option 'monitor_log_frequency'        = 12                                
 Config option 'monitor_fullscan_frequency'   = 12                                
``` 

The paths are all correct and i have tripple checked them - but for whatever reason it still default to /root/onedrive which cause all the onedrive files downloaded inside the docker container instead of the mapped volume.

What did I do wrong? How do i fix this please?

Thanks

**Comment by abraunegg** [comment]
@fliptoback 
Please learn to use triple back ticks for code|console|config output - it makes life easier to read that output.

**Comment by abraunegg** [comment, marked as answer]
@fliptoback 
Please read the Docker | Podman documentation to ensure that:

1. You are installing Docker the *correct* way - ie - if you are on Ubuntu or any platform that is derived from Ubuntu - you are *not* using the Ubuntu provided Docker packages as they are broken. Please ensure you install Docker the *correct* way (or use a better distribution and stop using Ubuntu)
2. The container you are using `image: driveone/onedrive:latest` is not the recommended one. Please switch this to `edge` as per the documentation.

> The paths are all correct and i have tripple checked them - but for whatever reason it still default to /root/onedrive which cause all the onedrive files downloaded inside the docker container instead of the mapped volume.
>
> What did I do wrong? How do i fix this please?

What you are looking at is the *static* application configuration when you *manually* run `--display-config` from within the Docker container. It has several logic areas that uses the 'environment' variables it is running in to display this output + using configuration option data.

A better option for you is to enable these 2 variables:

* ONEDRIVE_DISPLAY_CONFIG
* ONEDRIVE_VERBOSE

The first will display the *actual* config the client is using at runtime. For your Docker scenario this is going to be better for you as this is displayed with all the options / arguments passed in. The key ones here are:
```
# Default parameters
ARGS=(--confdir /onedrive/conf --syncdir /onedrive/data)
echo "# Base Args: ${ARGS[@]}"
```

These then tell the client:
* Where to store the configuration file
* What syncdir to use

In a Docker scenario, with your configuration:
```
volumes:
       - /volume1/docker/onedrive_user3:/onedrive/conf      
       - /volume2/onedrive2/johndoe:/onedrive/data
```

The client will store the configuration files in the volume `/onedrive/conf` which you have mapped to `/volume1/docker/onedrive_user3` and the data will be stored in `/onedrive/data` which is mapped to `/volume2/onedrive2/johndoe`

It is easy to see why if you are manually entering the container and then manually running `--display-config` and not seeing the expected output, however adding the `ONEDRIVE_DISPLAY_CONFIG` variable and running the container should then give you the right details.

**Reply by fliptoback** [reply]
Hi Abraunegg,

Thanks so much for your help.

I have now updated the docker-compose file. I am running this in my synology nas by the way, so it was whatever latest docker it came with. So hoping that the docker environment is not an issue here.

The updated docker-compose file is as follows:

```
version: "3.7"
services:
  onedrive_user3:
    image: driveone/onedrive:edge
    container_name: onedrive_user3
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - ONEDRIVE_UID=1026
      - ONEDRIVE_GID=100
      - ONEDRIVE_DISPLAY_CONFIG=1
      - ONEDRIVE_VERBOSE=1
    volumes:
      - /volume1/docker/onedrive_user3:/onedrive/conf
      - /volume2/onedrive2/johndoe:/onedrive/data
#    command: --resync --monitor --confdir /onedrive/conf  # only enable this if we need resync to run
    command: --monitor --confdir /onedrive/conf  # Auto sync in monitor mode      
    restart: unless-stopped
```

When the docker container starts, I can see in the log that:

```
# Running container as user: onedrive
# Base Args: --confdir /onedrive/conf --syncdir /onedrive/data
# We run in Monitor Mode
# Adding --monitor
# We are being verbose
# Adding --verbose
# We are printing the application running configuration at application startup
# Adding --display-running-config
# Changing ownership permissions on /onedrive/data and /onedrive/conf to onedrive:users
# Launching 'onedrive' as onedrive via gosu
Reading configuration file: /onedrive/conf/config
Configuration file successfully loaded
Using IPv4 and IPv6 (if configured) for all network operations
Attempting to contact Microsoft OneDrive Login Service
Successfully reached Microsoft OneDrive Login Service
Configuring Global Azure AD Endpoints
```

So seems things are working and it is beginning to sync to the right folder this time round. 

I also log into the console of the container and type:
onedrive --display-config
and it still show 
```
Config option 'sync_dir'                     = ~/OneDrive   
```
but you have explained that this is a "static" setup so that should be ignored.

Things are appearing to work now - although there are a lot of errors like:

The parent items are not in the database

I am googling how to solve this one in the interim.

Many thanks again for your help!
