### ISSUE TITLE
Docker not syncing local deletions 

### ISSUE THREAD

**Issue by JTT-JustTheTip** [abraunegg/onedrive#1044]
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
Docker instance will not sync any local deletions, when container restarted it downloads all deleted folders and files instead of syncing changes.

Any files or folders made locally will be synced to onedrive. Only deletions will not sync.

**Application and Operating System Details:**
Ubuntu 18.04.4 LTS 
Docker 18.09.5
OneDrive Personal 

Docker Compose -
```

version: '2'
services:
  OneDrive:
    image: driveone/onedrive
    container_name: onedrive
    hostname: onedrive
    restart: unless-stopped
    tty: true
    environment:
      ONEDRIVE_UID: '1001'
      ONEDRIVE_GID: '1001'
    volumes:
      - /media/AlphaData/Spencer-Area/OneDrive-DockerTest/:/onedrive/data
      - /Docker_Configs/OneDrive/config:/onedrive/conf
    
    
```

OneDrive Config
```

# Configuration for OneDrive Linux Client
# This file contains the list of supported configuration fields
# with their default values.
# All values need to be enclosed in quotes
# When changing a config option below, remove the '#' from the start of the line
# For explanations of all config options below see docs/USAGE.md or the man page.
#
# sync_dir = "~/OneDrive"
# skip_file = "~*|.~*|*.tmp"
monitor_interval = "10"
# skip_dir = ""
log_dir = "/onedrive/conf/logs"
# drive_id = ""
upload_only = "false"
# check_nomount = "false"
# check_nosync = "false"
download_only = "false"
# disable_notifications = "false"
# disable_upload_validation = "false"
enable_logging = "true"
# force_http_11 = "false"
# force_http_2 = "false"
local_first = "false"
# no_remote_delete = "false"
# skip_symlinks = "false"
# debug_https = "false"
# skip_dotfiles = "false"
# dry_run = "false"
# min_notify_changes = "5"
# monitor_log_frequency = "5"
monitor_fullscan_frequency = "5"
sync_root_files = "true"
# classify_as_big_delete = "1000"
# user_agent = ""
# remove_source_files = "false"
# skip_dir_strict_match = "false"
# application_id = ""
resync = "true"
# bypass_data_preservation = "false"
~
~
~
~

```

Docker Logs 

```
+ : 1001
,++ getent group 1001
,+ odgroup=
,+ odgroup=onedrive
,+ groupadd onedrive -g 1001
,++ getent passwd 1001
,+ oduser=
,+ oduser=onedrive
,+ useradd -m onedrive -u 1001 -g 1001
,+ chown onedrive:onedrive /onedrive/ /onedrive/conf
,+ ARGS=(--monitor --confdir /onedrive/conf --syncdir /onedrive/data)
,+ '[' 0 == 1 ']'
,+ '[' 0 -gt 0 ']'
,+ exec gosu onedrive /usr/local/bin/onedrive --monitor --confdir /onedrive/conf --syncdir /onedrive/data
,Configuration file successfully loaded
,Configuring Global Azure AD Endpoints
,Initializing the Synchronization Engine ...
,Initializing monitor ...
,OneDrive monitor interval (seconds): 10
,Downloading file New Text Document.txt ... done.
,Downloading file meme.txt ... done.

```

I had previously deleted those text files locally and the changes did not sync so as a result when the container was restarted it downloaded them.

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:

1. Make file locally or on another device, wait for file to be present on both
2. Delete file locally 
3. File deletion will not sync
4. Restart container
5. Container will download file
