### ISSUE TITLE
Could not initialize the OneDrive API

### ISSUE THREAD

**Issue by 81pla** [abraunegg/onedrive#1241]
use driveone/onedrive:latest

my docker-compose.yml

```
version: '3.5'

services:
    onedrive:
        image: driveone/onedrive:latest
        restart: unless-stopped
        environment:
            - ONEDRIVE_UID=1000
            - ONEDRIVE_GID=1000
        dns:
            - 114.114.114.114
        volumes: 
            - /home/onedrive/conf:/onedrive/conf
            - /home/onedrive/data:/onedrive/data
```

when i ```docker-compose up -d ```   the contianer will stop soon.

the logs shows

```
Attaching to onedrive_onedrive_1
onedrive_1  | + : 1000
onedrive_1  | + : 1000
onedrive_1  | ++ getent group 1000
onedrive_1  | + odgroup=
onedrive_1  | + odgroup=onedrive
onedrive_1  | + groupadd onedrive -g 1000
onedrive_1  | ++ getent passwd 1000
onedrive_1  | + oduser=
onedrive_1  | + oduser=onedrive
onedrive_1  | + useradd -m onedrive -u 1000 -g 1000
onedrive_1  | + chown onedrive:onedrive /onedrive/ /onedrive/conf
onedrive_1  | + ARGS=(--monitor --confdir /onedrive/conf --syncdir /onedrive/data)
onedrive_1  | + '[' 0 == 1 ']'
onedrive_1  | + '[' 0 == 1 ']'
onedrive_1  | + '[' 0 == 1 ']'
onedrive_1  | + '[' 0 == 1 ']'
onedrive_1  | + '[' 0 == 1 ']'
onedrive_1  | + '[' 0 == 1 ']'
onedrive_1  | + '[' 0 -gt 0 ']'
onedrive_1  | + exec gosu onedrive /usr/local/bin/onedrive --monitor --confdir /onedrive/conf --syncdir /onedrive/data
onedrive_1  | Configuring Global Azure AD Endpoints
onedrive_1  | Authorize this app visiting:
onedrive_1  | 
onedrive_1  | https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=d50ca740-c83f-4d1b-b616-12c519384f0c&scope=Files.ReadWrite%20Files.ReadWrite.all%20Sites.Read.All%20Sites.ReadWrite.All%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient
onedrive_1  | 
onedrive_1  | Enter the response uri: Could not initialize the OneDrive API
onedrive_1  | Invalid uri
onedrive_1  | Configuring Global Azure AD Endpoints
onedrive_1  | Authorize this app visiting:
onedrive_1  | 
onedrive_1  | https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=d50ca740-c83f-4d1b-b616-12c519384f0c&scope=Files.ReadWrite%20Files.ReadWrite.all%20Sites.Read.All%20Sites.ReadWrite.All%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient
onedrive_1  | 
onedrive_1  | Enter the response uri: Invalid uri
onedrive_1  | Could not initialize the OneDrive API
onedrive_onedrive_1 exited with code 3
```

what should i do?

```
onedrive_1  | Enter the response uri: Invalid uri
onedrive_1  | Could not initialize the OneDrive API
```
