### ISSUE TITLE
Container Stops because a --resync is required

### ISSUE THREAD

**Issue by ggritzan** [abraunegg/onedrive#1640]
### Bug Report Details ###
**Description**
I tried to start the onedrive client with docker-compose. The container restarts permanently a returns the following message:
``` bash
onedrive_1  | + : 1000
onedrive_1  | + : 1000
onedrive_1  | ++ getent group 1000
onedrive_1  | + odgroup=onedrive:x:1000
onedrive_1  | + odgroup=onedrive
onedrive_1  | ++ getent passwd 1000
onedrive_1  | + oduser=onedrive:x:1000:1000::/home/onedrive:/bin/ash
onedrive_1  | + oduser=onedrive
onedrive_1  | + usermod -g onedrive onedrive
onedrive_1  | usermod: no changes
onedrive_1  | + grep -qv root /dev/fd/63
onedrive_1  | ++ groups onedrive
onedrive_1  | + chown onedrive:onedrive /onedrive/ /onedrive/conf
onedrive_1  | + ARGS=(--monitor --confdir /onedrive/conf --syncdir /onedrive/data)
onedrive_1  | + '[' 0 == 1 ']'
onedrive_1  | + '[' 0 == 1 ']'
onedrive_1  | + '[' 0 == 1 ']'
onedrive_1  | + '[' 0 == 1 ']'
onedrive_1  | + '[' 0 == 1 ']'
onedrive_1  | + '[' 0 == 1 ']'
onedrive_1  | + '[' 0 -gt 0 ']'
onedrive_1  | + exec gosu onedrive /usr/local/bin/onedrive --monitor --confdir /onedrive/conf --syncdir /onedrive/data
onedrive_1  | Configuration file successfully loaded
onedrive_1  | config file has been updated, checking if --resync needed
onedrive_1  | An application configuration change has been detected where a --resync is required
```
I perfomed step 3 as mentioned in the Readme with the command:
``` bash
docker run -it --name onedrive -v /${HOME}/Dokumente/One-Drive-Sync-Tool/config:/onedrive/conf -v "/{$HOME}/OneDrive:/onedrive/data" -e "ONEDRIVE_UID:1000" -e "ONEDRIVE_GID:1000" driveone/onedrive:alpine --resync
```

**Application and Operating System Details:**
*   20.04.1-Ubuntu
*   Gui installed
*   OneDrive Account Type: private

``` yml
version: "3"
services:
    onedrive:
        image: driveone/onedrive:alpine
        restart: unless-stopped
        environment:
            - ONEDRIVE_UID=1000
            - ONEDRIVE_GID=1000
        volumes:
            - /${HOME}/Dokumente/One-Drive-Sync-Tool/config:/onedrive/conf
            - /${HOME}/OneDrive:/onedrive/data
```
