### ISSUE TITLE
Running OneDrive in Docker for the first time

### ISSUE THREAD

**Issue by GentleHoneyLover** [abraunegg/onedrive#1747]
Hi,

Trying to run your client in Docker for the first time.

Using the following compose setup:

```yaml
  onedrive:
    container_name: onedrive
    image: docker.io/driveone/onedrive:alpine
    restart: unless-stopped
    environment:
      - ONEDRIVE_UID=997
      - ONEDRIVE_GID=997
    volumes:
      - /mnt/data/container-volumes/onedrive/conf:/onedrive/conf
      - /mnt/data/container-volumes/onedrive/data:/onedrive/data
```

After I bring the compose file up the container stays on the "Restarting" state all the time:

```bash
     Name                   Command                  State                                                                   Ports
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
onedrive         /entrypoint.sh                   Restarting
```

`docker logs onedrive` keep showing this:

```bash
+ : 997
+ : 997
++ getent group 997
+ odgroup=
+ odgroup=onedrive
+ groupadd onedrive -g 997
++ getent passwd 997
+ oduser=
+ oduser=onedrive
+ useradd -m onedrive -u 997 -g 997
+ chown onedrive:onedrive /onedrive/ /onedrive/conf
+ ARGS=(--monitor --confdir /onedrive/conf --syncdir /onedrive/data)
+ '[' 0 == 1 ']'
+ '[' 0 == 1 ']'
+ '[' 0 == 1 ']'
+ '[' 0 == 1 ']'
+ '[' 0 == 1 ']'
+ '[' 0 == 1 ']'
+ '[' 0 -gt 0 ']'
+ exec gosu onedrive /usr/local/bin/onedrive --monitor --confdir /onedrive/conf --syncdir /onedrive/data
Configuring Global Azure AD Endpoints
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=d50ca740-c83f-4d1b-b616-12c519384f0c&scope=Files.ReadWrite%20Files.ReadWrite.all%20Sites.Read.All%20Sites.ReadWrite.All%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient
```

Tried opening the URL in a browser. After logging in nothing happens. Container continues to struggle...

Am I doing something wrong? Can you please help me figure this out?

Thanks for your support in advance!
