### ISSUE TITLE
ARMHF: Building in a docker-compose file straight from the repo does not work

### ISSUE THREAD

**Issue by fl0r1s** [abraunegg/onedrive#965]
### Bug Report Details ###
**Describe the bug**

Build fails when building docker straight from repository.

While building the docker for an ARMHF device (Raspberry pi 4) straight from the repository as follows: 
```
  onedrive:
    image: local-onedrive
    build: 
      context: 'https://github.com/abraunegg/onedrive.git'
      dockerfile: contrib/docker/Dockerfile-rpi # dockerfile relative to repo root
    restart: unless-stopped
    environment:
      - ONEDRIVE_UID=${PUID}
      - ONEDRIVE_GID=${PGID}
    volumes: 
      - ${CONFIG_DIR}/onedrive:/onedrive/conf
      - ${ONEDRIVE_DIR}:/onedrive/data
```
I get the following error: 
```
Building onedrive
Step 1/10 : FROM debian:stretch
 ---> 6e658fcd1761
Step 2/10 : RUN apt update &&     apt install -y build-essential curl libcurl4-openssl-dev libsqlite3-dev pkg-config wget git
 ---> Using cache
 ---> 01faed3da36c
Step 3/10 : RUN wget https://github.com/ldc-developers/ldc/releases/download/v1.16.0/ldc2-1.16.0-linux-armhf.tar.xz &&     tar -xvf ldc2-1.16.0-linux-armhf.tar.xz
 ---> Using cache
 ---> a1586dd70e21
Step 4/10 : COPY . /usr/src/onedrive
 ---> 9b139994ef81
Step 5/10 : RUN cd /usr/src/onedrive/ &&     ./configure DC=/ldc2-1.16.0-linux-armhf/bin/ldmd2 &&     make clean &&     make &&     make install
 ---> Running in 88b76309111c
checking for a BSD-compatible install... /usr/bin/install -c
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dmd... /ldc2-1.16.0-linux-armhf/bin/ldmd2
checking version of D compiler... 1.16.0
checking for curl... yes
checking for sqlite... yes
Package systemd was not found in the pkg-config search path.
Perhaps you should add the directory containing `systemd.pc'
to the PKG_CONFIG_PATH environment variable
No package 'systemd' found
Package systemd was not found in the pkg-config search path.
Perhaps you should add the directory containing `systemd.pc'
to the PKG_CONFIG_PATH environment variable
No package 'systemd' found
configure: creating ./config.status
config.status: creating Makefile
config.status: creating contrib/pacman/PKGBUILD
config.status: creating contrib/spec/onedrive.spec
config.status: creating onedrive.1
config.status: creating contrib/systemd/onedrive.service
config.status: creating contrib/systemd/onedrive@.service
rm -f onedrive onedrive.o version
rm -rf autom4te.cache
rm -f config.log config.status
if [ -f .git/HEAD ] ; then \
        git describe --tags > version ; \
else \
        echo v2.4.3-dev > version ; \
fi
fatal: No names found, cannot describe anything.
Makefile:99: recipe for target 'onedrive' failed
make: *** [onedrive] Error 128
ERROR: Service 'onedrive' failed to build: The command '/bin/sh -c cd /usr/src/onedrive/ &&     ./configure DC=/ldc2-1.16.0-linux-armhf/bin/ldmd2 &&     make clean &&     make &&     make install' returned a non-zero code: 2
```

It first fails on not being able to find `systemd`. Next, it fails on [makefile line 99](https://github.com/abraunegg/onedrive/blob/master/Makefile.in#L99) trying to get tags from the repo. After some googling I have found that this docker build context is a shallow clone which is not allowed. 

## Machine Info
OS: `Linux naspi 4.19.102-v7l+ #1295 SMP Thu Feb 6 15:49:36 GMT 2020 armv7l GNU/Linux`
Headless
OneDrive Account type: not important
DMD / LDC: I use the [raspberry pi dockerfile](https://github.com/abraunegg/onedrive/blob/master/contrib/docker/Dockerfile-rpi). This uses LDC.
Application configuration: not important
Curl version: not important

Can someone please aid me in solving this issue. It would be really nice to build for armhf devices straight from the github repo  using the file provided in the contrib folder.
